// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TkoolMV_PluginCommandBook","status":true,"description":"プラグインコマンド集","parameters":{"制御文字の拡張":"はい"}},
{"name":"CustomizeConfigDefault","status":true,"description":"Optionsデフォルト値設定プラグイン","parameters":{"alwaysDash":"ON","commandRemember":"OFF","bgmVolume":"100","bgsVolume":"100","meVolume":"100","seVolume":"100"}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"MapRapid","status":true,"description":"マップ高速化プラグイン","parameters":{"showMessageRapid":"ON","windowOpenRapid":"ON"}}
];
